name: call
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_info_plus: ^11.5.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  file_picker: ^10.2.0
  intl_phone_field: ^3.2.0
  image_picker: ^1.0.7
  firebase_storage: ^12.4.7
  csv: ^6.0.0
  url_launcher: ^6.2.5
  get_it: ^8.0.3
  http: ^1.2.1
  excel: ^4.0.6
  flutter_tts: ^4.2.3
  speech_to_text: ^7.1.0
  flutter_phone_direct_caller: ^2.1.1
  permission_handler: ^12.0.0+1
  path_provider: ^2.0.11
  qr_flutter: ^4.1.0
  google_sign_in: ^7.0.0
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  google_api_headers: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sample_contacts.csv
