name: callai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.2
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.13.6
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  file_picker: ^8.0.7
  intl_phone_field: ^3.2.0
  image_picker: ^1.0.7
  firebase_storage: ^11.6.5
  csv: ^5.0.2
  url_launcher: ^6.2.4
  get_it: ^7.6.7
  http: ^1.2.1
  excel: ^4.0.6
  flutter_tts: ^3.8.5
  speech_to_text: ^7.0.0
  flutter_phone_direct_caller: ^2.1.0
  phone_state: ^2.1.1
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 